// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package procevents

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processExecEvent struct {
	_ structs.HostLayout
	H struct {
		_     structs.HostLayout
		Ts    uint64
		Start uint64
		Kind  uint32
		Pid   uint32
		Ppid  uint32
		Uid   uint32
		Comm  [16]int8
	}
	Flags    uint32
	ArgsLen  uint32
	Filename [512]int8
	Args     [4096]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	processMapDrops          = "drops"
	processMapEvents         = "events"
	processMapScratch        = "scratch"
	processProgOnExec        = "on_exec"
	processProgOnExit        = "on_exit"
	processProgOnFork        = "on_fork"
	processVarLiveAtLastExit = "live_at_last_exit"
)

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	OnExec *ebpf.ProgramSpec `ebpf:"on_exec"`
	OnExit *ebpf.ProgramSpec `ebpf:"on_exit"`
	OnFork *ebpf.ProgramSpec `ebpf:"on_fork"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	Drops   *ebpf.MapSpec `ebpf:"drops"`
	Events  *ebpf.MapSpec `ebpf:"events"`
	Scratch *ebpf.MapSpec `ebpf:"scratch"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
	LiveAtLastExit *ebpf.VariableSpec `ebpf:"live_at_last_exit"`
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	Drops   *ebpf.Map `ebpf:"drops"`
	Events  *ebpf.Map `ebpf:"events"`
	Scratch *ebpf.Map `ebpf:"scratch"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.Drops,
		m.Events,
		m.Scratch,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
	LiveAtLastExit *ebpf.Variable `ebpf:"live_at_last_exit"`
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	OnExec *ebpf.Program `ebpf:"on_exec"`
	OnExit *ebpf.Program `ebpf:"on_exit"`
	OnFork *ebpf.Program `ebpf:"on_fork"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.OnExec,
		p.OnExit,
		p.OnFork,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_arm64_bpfel.o
var _ProcessBytes []byte
